version: '3.5'

services: 
  db:
    image: postgres
    container_name: postgre_server
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - poc_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "unisenha"
    networks: 
      - poc-network

  kafka_cluster:
    image: lensesio/fast-data-dev
    container_name: kafka_cluster
    restart: always
    ports: 
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "2181:2181"
      - "3030:3030"
    environment:
      ADV_HOST: 192.168.10.189
      # ADV_HOST: 192.168.10.189
    networks: 
      - poc-network

  processador:
    image: martinsweliton/msv-processador-poc
    container_name: msv-processador
    restart: always
    depends_on: 
      - kafka_cluster
      - db
    ports: 
      - "9091-9099:8080"
    environment:
      IP_KAFKA_SERVER: kafka_cluster
      KAFKA_PORT: 9092 
      POSTGRE_URL: db
      POSTGRE_PORT: 5432
      POSTGRE_DATABASE: postgres
      POSTGRE_USER: postgres
      POSTGRE_PASS: unisenha
    links:
      - kafka_cluster
    networks: 
      - rango-network

 
networks:
  poc-network:
    driver: bridge
           
volumes:
  poc_data: